baseURL = "https://www.zx81.org.uk/"
languageCode = "en-gb"
theme = "anubis2"
title = "This is ZX81.org.uk"

copyright = 'Â© Stephen Darlington'
[params.author]
name = "Stephen Darlington"

[params]
description = "Ponderings on software, the universe and everything by Stephen Darlington (a human) since 1999."
dateFormat = "2006-01-02"
paginationSinglePost = true

anubis2.colorTheme = "auto"
anubis2.enableColorThemeSwitcher = true

anubis2.enableReadMoreButton = true
anubis2.readNextPosts = 3
anubis2.enablecopycodebutton = true
anubis2.enableRssIcon = true
anubis2.enableSummary = true
locale = "en-gb"
anubis2.enableMathGlobally = false # true: enable mathjax globally (default is false)
anubis2.tocWordCount = true

anubis2.socialIcons = [
    { id = "github", url = "https://github.com/sdarlington" },
    { id = "linkedin", url = "https://www.linkedin.com/in/stephendarlington/" },
    { id = "mastodon", url = "https://mas.to/@sdarlington" },
]

[services]
  [services.rss]
    limit = 20

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "software"
name = "Software"
url = "/software/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 5

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Chroma style, find more at here: https://swapoff.org/chroma/playground/
